/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SimplePortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<{
    _key: string;
  } & Link>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type ImageObject = {
  _type: "imageObject";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  caption?: string;
  align?: "left" | "center" | "right";
  size?: "full" | "large" | "medium" | "small";
};

export type ImageGroup = {
  _type: "imageGroup";
  image1?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt1?: string;
  image2?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt2?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  SEO?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  openGraphTitle?: string;
  openGraphDescription?: string;
  openGraphImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navList?: Array<{
    _key: string;
  } & Link>;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navList?: Array<{
    _key: string;
  } & Link>;
};

export type Architecture = {
  _id: string;
  _type: "architecture";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug: Slug;
  visitLink?: string;
  author: string;
  location: string;
  address: string;
  descriptionProt?: SimplePortableText;
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  descriptionProt2?: SimplePortableText;
  section2?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      _key: string;
    } & Link>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
  } & ImageObject | {
    _key: string;
  } & ImageGroup>;
  imageCourtesy?: Array<{
    title?: string;
    url?: string;
    _type: "imageCourtesy";
    _key: string;
  }>;
  footerButton?: CallToAction;
  metaTitle?: string;
  metaDesc?: string;
};

export type CallToAction = {
  _type: "callToAction";
  linkText?: string;
  url?: string;
};

export type Link = {
  _type: "link";
  text?: string;
  type: string;
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homepage";
  };
  url?: string;
  email?: string;
  phone?: string;
  value?: string;
  blank?: boolean;
  parameters?: string;
  anchor?: string;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerColor?: "dark" | "light" | "lightOnMobile";
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = SimplePortableText | ImageObject | ImageGroup | SiteSettings | Seo | Footer | Header | Architecture | CallToAction | Link | Homepage | Page | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == 'siteSettings'][0] {        SEO {    ...,    'openGraphImage': openGraphImage.asset->url,},    }
export type SiteSettingsQueryResult = {
  SEO: {
    _type: "seo";
    metaTitle?: string;
    metaDescription?: string;
    openGraphTitle?: string;
    openGraphDescription?: string;
    openGraphImage: string | null;
  } | null;
} | null;
// Variable: headerQuery
// Query: *[_type == 'header'][0] {        navList[] {    ...,    internalLink->{_type,slug,title}},    }
export type HeaderQueryResult = {
  navList: Array<{
    _key: string;
    _type: "link";
    text?: string;
    type: string;
    internalLink: {
      _type: "homepage";
      slug: null;
      title: null;
    } | {
      _type: "page";
      slug: Slug;
      title: string;
    } | null;
    url?: string;
    email?: string;
    phone?: string;
    value?: string;
    blank?: boolean;
    parameters?: string;
    anchor?: string;
  }> | null;
} | null;
// Variable: footerQuery
// Query: *[_type == 'footer'][0] {        navList[] {    ...,    internalLink->{_type,slug,title}},    }
export type FooterQueryResult = {
  navList: Array<{
    _key: string;
    _type: "link";
    text?: string;
    type: string;
    internalLink: {
      _type: "homepage";
      slug: null;
      title: null;
    } | {
      _type: "page";
      slug: Slug;
      title: string;
    } | null;
    url?: string;
    email?: string;
    phone?: string;
    value?: string;
    blank?: boolean;
    parameters?: string;
    anchor?: string;
  }> | null;
} | null;
// Variable: allArchitectureQuery
// Query: *[_type == 'architecture'] | order(title asc) {        title,        "slug": slug.current,        location,    }
export type AllArchitectureQueryResult = Array<{
  title: string | null;
  slug: string;
  location: string;
}>;
// Variable: architectureQuery
// Query: *[_type == 'architecture' && slug.current == $slug][0] {        "slug": slug.current,        visitLink,        author,        location,        address,        descriptionProt,        gallery[] {    caption,    'assetId': asset->_id,    'assetPath': asset->path,    'aspectRatio': asset->metadata.dimensions.aspectRatio,},        descriptionProt2,        section2,        imageCourtesy,        footerButton,        metaTitle,        metaDesc,    }
export type ArchitectureQueryResult = {
  slug: string;
  visitLink: string | null;
  author: string;
  location: string;
  address: string;
  descriptionProt: SimplePortableText | null;
  gallery: Array<{
    caption: null;
    assetId: string | null;
    assetPath: string | null;
    aspectRatio: number | null;
  }> | null;
  descriptionProt2: SimplePortableText | null;
  section2: Array<{
    _key: string;
  } & ImageGroup | {
    _key: string;
  } & ImageObject | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      _key: string;
    } & Link>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  imageCourtesy: Array<{
    title?: string;
    url?: string;
    _type: "imageCourtesy";
    _key: string;
  }> | null;
  footerButton: CallToAction | null;
  metaTitle: string | null;
  metaDesc: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n    *[_type == 'siteSettings'][0] {\n        SEO {\n    ...,\n    'openGraphImage': openGraphImage.asset->url,\n},\n    }\n": SiteSettingsQueryResult;
    "\n    *[_type == 'header'][0] {\n        navList[] {\n    ...,\n    internalLink->{_type,slug,title}\n},\n    }\n": HeaderQueryResult;
    "\n    *[_type == 'footer'][0] {\n        navList[] {\n    ...,\n    internalLink->{_type,slug,title}\n},\n    }\n": FooterQueryResult;
    "\n    *[_type == 'architecture'] | order(title asc) {\n        title,\n        \"slug\": slug.current,\n        location,\n    }\n": AllArchitectureQueryResult;
    "\n    *[_type == 'architecture' && slug.current == $slug][0] {\n        \"slug\": slug.current,\n        visitLink,\n        author,\n        location,\n        address,\n        descriptionProt,\n        gallery[] {\n    caption,\n    'assetId': asset->_id,\n    'assetPath': asset->path,\n    'aspectRatio': asset->metadata.dimensions.aspectRatio,\n},\n        descriptionProt2,\n        section2,\n        imageCourtesy,\n        footerButton,\n        metaTitle,\n        metaDesc,\n    }\n": ArchitectureQueryResult;
  }
}
